/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:metadata
 * Source: Individual metadata.ts files in src/games/ and src/apps/
 */

import type { CategoryId } from "./game-registry";

export interface GameMetadata {
  name: string;
  icon: string;
  color: string;
  description: string;
  category: CategoryId;
}

export const GAME_METADATA: Record<string, GameMetadata> = {
  "2048": {
    name: "2048",
    icon: "🔢",
    color: "orange",
    description: "Slide and merge numbers",
    category: "arcade",
  },
  "asteroids": {
    name: "Asteroids",
    icon: "☄️",
    color: "orange",
    description: "Vector space shooter",
    category: "arcade",
  },
  "blitz-bomber": {
    name: "Blitz Bomber",
    icon: "✈️",
    color: "cyan",
    description: "WWII bombing run",
    category: "action",
  },
  "bomberman": {
    name: "Bomberman",
    icon: "💣",
    color: "cyan",
    description: "Grid-based bomb action",
    category: "action",
  },
  "breakout": {
    name: "Breakout",
    icon: "🧱",
    color: "orange",
    description: "Brick breaker with power-ups",
    category: "arcade",
  },
  "checkers": {
    name: "Checkers",
    icon: "🔴",
    color: "amber",
    description: "Classic checkers game",
    category: "board",
  },
  "chess": {
    name: "Chess",
    icon: "♟️",
    color: "amber",
    description: "Classic chess game",
    category: "board",
  },
  "cookie-clicker": {
    name: "Cookie Clicker",
    icon: "🍪",
    color: "purple",
    description: "Click cookies, buy upgrades",
    category: "puzzle",
  },
  "dino-runner": {
    name: "Dino Runner",
    icon: "🦖",
    color: "green",
    description: "Chrome-style endless runner",
    category: "racing",
  },
  "endless-runner": {
    name: "Endless Runner",
    icon: "🏃‍♂️",
    color: "cyan",
    description: "Run forever, dodge obstacles",
    category: "action",
  },
  "flappy-bird": {
    name: "Flappy Bird",
    icon: "🐦",
    color: "orange",
    description: "Tap to fly through pipes",
    category: "arcade",
  },
  "hextris": {
    name: "Hextris",
    icon: "⬡",
    color: "purple",
    description: "Hexagon color matching",
    category: "puzzle",
  },
  "hill-climb": {
    name: "Hill Climb",
    icon: "🏔️",
    color: "green",
    description: "Physics-based hill climbing",
    category: "racing",
  },
  "math-attack": {
    name: "Math Attack",
    icon: "🔢",
    color: "orange",
    description: "Solve math problems before they hit the ground",
    category: "arcade",
  },
  "memory-match": {
    name: "Memory Match",
    icon: "🧠",
    color: "purple",
    description: "Match the cards",
    category: "puzzle",
  },
  "monster-truck": {
    name: "Monster Truck",
    icon: "🚗",
    color: "green",
    description: "3D monster truck open world",
    category: "racing",
  },
  "oregon-trail": {
    name: "Oregon Trail",
    icon: "🤠",
    color: "violet",
    description: "Classic pioneer adventure",
    category: "retro",
  },
  "platformer": {
    name: "Platformer",
    icon: "🏃",
    color: "cyan",
    description: "Jump and run adventure",
    category: "action",
  },
  "quoridor": {
    name: "Quoridor",
    icon: "🧱",
    color: "amber",
    description: "Strategic wall-placing game",
    category: "board",
  },
  "retro-arcade": {
    name: "Retro Arcade",
    icon: "🕹️",
    color: "violet",
    description: "Classic console emulator",
    category: "retro",
  },
  "snake": {
    name: "Snake",
    icon: "🐍",
    color: "orange",
    description: "Classic snake game",
    category: "arcade",
  },
  "space-invaders": {
    name: "Space Invaders",
    icon: "👾",
    color: "orange",
    description: "Classic alien shooter",
    category: "arcade",
  },
  "wordle": {
    name: "Wordle",
    icon: "📝",
    color: "purple",
    description: "Guess the word with age-appropriate difficulty",
    category: "puzzle",
  },
  "drawing-app": {
    name: "Drawing",
    icon: "🎨",
    color: "pink",
    description: "Draw and create art",
    category: "apps",
  },
  "drum-machine": {
    name: "Drum Machine",
    icon: "🥁",
    color: "pink",
    description: "Make beats and loops",
    category: "apps",
  },
  "joke-generator": {
    name: "Jokes",
    icon: "😂",
    color: "pink",
    description: "Funny jokes for kids",
    category: "apps",
  },
  "toy-finder": {
    name: "Toy Finder",
    icon: "🧸",
    color: "pink",
    description: "Find cool toys",
    category: "apps",
  },
  "trivia": {
    name: "Trivia Quiz",
    icon: "🧠",
    color: "pink",
    description: "Test your knowledge with age-appropriate trivia questions",
    category: "apps",
  },
  "virtual-pet": {
    name: "Virtual Pet",
    icon: "🐣",
    color: "pink",
    description: "Raise your digital pet",
    category: "apps",
  },
  "weather": {
    name: "Weather",
    icon: "🌤️",
    color: "pink",
    description: "Check the weather",
    category: "apps",
  },
};

/**
 * Get metadata for a game by its appId.
 * Returns a default if game not found.
 */
export function getGameMetadata(appId: string): GameMetadata {
  return (
    GAME_METADATA[appId] || {
      name: appId,
      icon: "🎮",
      color: "gray",
      description: "A game",
      category: "arcade" as CategoryId,
    }
  );
}

/**
 * Static gradient class map - Tailwind can't analyze dynamic classes.
 */
const GRADIENT_MAP: Record<string, string> = {
  green: "from-green-500 to-green-700",
  red: "from-red-500 to-red-700",
  amber: "from-amber-500 to-amber-700",
  slate: "from-slate-500 to-slate-700",
  emerald: "from-emerald-500 to-emerald-700",
  sky: "from-sky-500 to-sky-700",
  orange: "from-orange-500 to-orange-700",
  lime: "from-lime-500 to-lime-700",
  purple: "from-purple-500 to-purple-700",
  yellow: "from-yellow-500 to-yellow-700",
  cyan: "from-cyan-500 to-cyan-700",
  blue: "from-blue-500 to-blue-700",
  pink: "from-pink-500 to-pink-700",
  stone: "from-stone-500 to-stone-700",
  indigo: "from-indigo-500 to-indigo-700",
  violet: "from-violet-500 to-violet-700",
  gray: "from-gray-500 to-gray-700",
};

/**
 * Get Tailwind background gradient classes for a game.
 */
export function getGameGradient(appId: string): string {
  const { color } = getGameMetadata(appId);
  return GRADIENT_MAP[color] || GRADIENT_MAP.gray;
}
