/**
 * Joke Generator Constants
 * Categories, types, and curated kid-friendly jokes
 * 500+ jokes total across all categories!
 */

// Joke categories
export const JOKE_CATEGORIES = [
  { id: "all", label: "All", emoji: "🎭" },
  { id: "dad-jokes", label: "Dad Jokes", emoji: "👨" },
  { id: "animals", label: "Animals", emoji: "🐶" },
  { id: "knock-knock", label: "Knock Knock", emoji: "🚪" },
  { id: "school", label: "School", emoji: "📚" },
  { id: "silly", label: "Silly", emoji: "🤪" },
  { id: "food", label: "Food", emoji: "🍕" },
] as const;

export type JokeCategory = (typeof JOKE_CATEGORIES)[number]["id"];

// Joke interface
export interface Joke {
  id: string;
  category: Exclude<JokeCategory, "all">;
  setup: string;
  punchline: string;
}

// Rating type
export type Rating = "funny" | "not-funny";

// ============================================================================
// CURATED KID-FRIENDLY JOKES (500+ jokes!)
// ============================================================================

export const CURATED_JOKES: Joke[] = [
  // ==========================================================================
  // ANIMALS (100+ jokes)
  // ==========================================================================
  { id: "animal-001", category: "animals", setup: "What do you call a sleeping dinosaur?", punchline: "A dino-snore!" },
  { id: "animal-002", category: "animals", setup: "What do you call a fish without eyes?", punchline: "A fsh!" },
  { id: "animal-003", category: "animals", setup: "Why don't elephants use computers?", punchline: "Because they're afraid of the mouse!" },
  { id: "animal-004", category: "animals", setup: "What do you call a bear with no teeth?", punchline: "A gummy bear!" },
  { id: "animal-005", category: "animals", setup: "Why do cows wear bells?", punchline: "Because their horns don't work!" },
  { id: "animal-006", category: "animals", setup: "What do you call a dog that does magic tricks?", punchline: "A Labracadabrador!" },
  { id: "animal-007", category: "animals", setup: "Why did the chicken join a band?", punchline: "Because it had the drumsticks!" },
  { id: "animal-008", category: "animals", setup: "What do you call an alligator in a vest?", punchline: "An investigator!" },
  { id: "animal-009", category: "animals", setup: "Why are cats bad storytellers?", punchline: "They only have one tale!" },
  { id: "animal-010", category: "animals", setup: "What do you call a lazy kangaroo?", punchline: "A pouch potato!" },
  { id: "animal-011", category: "animals", setup: "What do you call a fly without wings?", punchline: "A walk!" },
  { id: "animal-012", category: "animals", setup: "Why do bees have sticky hair?", punchline: "Because they use honeycombs!" },
  { id: "animal-013", category: "animals", setup: "What do you call a pig that knows karate?", punchline: "A pork chop!" },
  { id: "animal-014", category: "animals", setup: "What do you get when you cross a snake and a pie?", punchline: "A pie-thon!" },
  { id: "animal-015", category: "animals", setup: "Why don't oysters share?", punchline: "Because they're shellfish!" },
  { id: "animal-016", category: "animals", setup: "What do you call a cow with no legs?", punchline: "Ground beef!" },
  { id: "animal-017", category: "animals", setup: "Why did the duck go to the doctor?", punchline: "Because he was feeling a little down!" },
  { id: "animal-018", category: "animals", setup: "What do you call a deer with no eyes?", punchline: "No idea!" },
  { id: "animal-019", category: "animals", setup: "Why do seagulls fly over the sea?", punchline: "Because if they flew over the bay, they'd be bagels!" },
  { id: "animal-020", category: "animals", setup: "What do you call a monkey in a minefield?", punchline: "A ba-BOOM!" },
  { id: "animal-021", category: "animals", setup: "Why did the turtle cross the road?", punchline: "To get to the Shell station!" },
  { id: "animal-022", category: "animals", setup: "What do you call a sleeping bull?", punchline: "A bulldozer!" },
  { id: "animal-023", category: "animals", setup: "Why did the spider go to the computer?", punchline: "To check his web site!" },
  { id: "animal-024", category: "animals", setup: "What do you call a cat that eats lemons?", punchline: "A sour puss!" },
  { id: "animal-025", category: "animals", setup: "Why don't cats play poker?", punchline: "Too many cheetahs!" },
  { id: "animal-026", category: "animals", setup: "What do you call a cow in an earthquake?", punchline: "A milkshake!" },
  { id: "animal-027", category: "animals", setup: "Why did the bee get married?", punchline: "Because he found his honey!" },
  { id: "animal-028", category: "animals", setup: "What do you call a fish with two knees?", punchline: "A two-knee fish (tuna fish)!" },
  { id: "animal-029", category: "animals", setup: "Why are frogs so happy?", punchline: "They eat whatever bugs them!" },
  { id: "animal-030", category: "animals", setup: "What do you call a bird that's afraid to fly?", punchline: "Chicken!" },
  { id: "animal-031", category: "animals", setup: "Why did the cow go to Hollywood?", punchline: "To become a moo-vie star!" },
  { id: "animal-032", category: "animals", setup: "What do you call a penguin in the desert?", punchline: "Lost!" },
  { id: "animal-033", category: "animals", setup: "Why do fish live in salt water?", punchline: "Because pepper makes them sneeze!" },
  { id: "animal-034", category: "animals", setup: "What do you call a dog that's a librarian?", punchline: "A hush puppy!" },
  { id: "animal-035", category: "animals", setup: "Why did the octopus beat the shark in a fight?", punchline: "Because it was well armed!" },
  { id: "animal-036", category: "animals", setup: "What do you call a horse that lives next door?", punchline: "A neigh-bor!" },
  { id: "animal-037", category: "animals", setup: "Why did the elephant bring toilet paper to the party?", punchline: "Because he was a party pooper!" },
  { id: "animal-038", category: "animals", setup: "What do you call a rabbit with fleas?", punchline: "Bugs Bunny!" },
  { id: "animal-039", category: "animals", setup: "Why did the lion eat the tightrope walker?", punchline: "He wanted a well-balanced meal!" },
  { id: "animal-040", category: "animals", setup: "What do you call a snake that builds things?", punchline: "A boa constructor!" },
  { id: "animal-041", category: "animals", setup: "Why don't dogs make good dancers?", punchline: "They have two left feet!" },
  { id: "animal-042", category: "animals", setup: "What do you call a gorilla with a banana in each ear?", punchline: "Anything you want, he can't hear you!" },
  { id: "animal-043", category: "animals", setup: "Why did the dolphin cross the beach?", punchline: "To get to the other tide!" },
  { id: "animal-044", category: "animals", setup: "What's a frog's favorite candy?", punchline: "Lollihops!" },
  { id: "animal-045", category: "animals", setup: "What do you call a snake wearing a hard hat?", punchline: "A boa constructor!" },
  { id: "animal-046", category: "animals", setup: "Why did the elephant quit the circus?", punchline: "He was tired of working for peanuts!" },
  { id: "animal-047", category: "animals", setup: "What do you call a sheep covered in chocolate?", punchline: "A candy baa!" },
  { id: "animal-048", category: "animals", setup: "Why do pandas like old movies?", punchline: "Because they're in black and white!" },
  { id: "animal-049", category: "animals", setup: "What do you call a bee from America?", punchline: "A USB!" },
  { id: "animal-050", category: "animals", setup: "Why did the giraffe break up with the zebra?", punchline: "Because she was seeing someone taller!" },
  { id: "animal-051", category: "animals", setup: "What do you call a dinosaur that is sleeping?", punchline: "A dino-snore!" },
  { id: "animal-052", category: "animals", setup: "Why are elephants so wrinkled?", punchline: "Because they take too long to iron!" },
  { id: "animal-053", category: "animals", setup: "What do you call a dinosaur that crashes their car?", punchline: "Tyrannosaurus Wrecks!" },
  { id: "animal-054", category: "animals", setup: "Why did the pelican get kicked out of the restaurant?", punchline: "His bill was too big!" },
  { id: "animal-055", category: "animals", setup: "What's a cat's favorite color?", punchline: "Purrrple!" },
  { id: "animal-056", category: "animals", setup: "What do you call a fish that wears a bowtie?", punchline: "Sofishticated!" },
  { id: "animal-057", category: "animals", setup: "Why did the crab never share?", punchline: "Because he's shellfish!" },
  { id: "animal-058", category: "animals", setup: "What do you call a cold dog sitting on a rabbit?", punchline: "A chili dog on a bun!" },
  { id: "animal-059", category: "animals", setup: "Why did the lizard go to the doctor?", punchline: "Because of a reptile dysfunction!" },
  { id: "animal-060", category: "animals", setup: "What do you call a parrot that flew away?", punchline: "A polygon!" },
  { id: "animal-061", category: "animals", setup: "Why did the turkey cross the road twice?", punchline: "To prove he wasn't chicken!" },
  { id: "animal-062", category: "animals", setup: "What's a shark's favorite sandwich?", punchline: "Peanut butter and jellyfish!" },
  { id: "animal-063", category: "animals", setup: "Why do hummingbirds hum?", punchline: "Because they don't know the words!" },
  { id: "animal-064", category: "animals", setup: "What do you call a dinosaur with an extensive vocabulary?", punchline: "A thesaurus!" },
  { id: "animal-065", category: "animals", setup: "Why did the snake cross the road?", punchline: "To get to the other sssside!" },
  { id: "animal-066", category: "animals", setup: "What do you call a bear caught in the rain?", punchline: "A drizzly bear!" },
  { id: "animal-067", category: "animals", setup: "Why don't elephants like to swim?", punchline: "Because they can't keep their trunks up!" },
  { id: "animal-068", category: "animals", setup: "What do you call an owl that does magic?", punchline: "Hoo-dini!" },
  { id: "animal-069", category: "animals", setup: "Why did the pig become an actor?", punchline: "Because he was a real ham!" },
  { id: "animal-070", category: "animals", setup: "What's a mouse's favorite game?", punchline: "Hide and squeak!" },
  { id: "animal-071", category: "animals", setup: "Why did the cat sit on the computer?", punchline: "To keep an eye on the mouse!" },
  { id: "animal-072", category: "animals", setup: "What do you call a chicken at the North Pole?", punchline: "Lost!" },
  { id: "animal-073", category: "animals", setup: "Why don't leopards play hide and seek?", punchline: "Because they're always spotted!" },
  { id: "animal-074", category: "animals", setup: "What's a cow's favorite holiday?", punchline: "Moo Year's Day!" },
  { id: "animal-075", category: "animals", setup: "Why did the rooster go to KFC?", punchline: "He wanted to see a chicken strip!" },
  { id: "animal-076", category: "animals", setup: "What do you call a cat who eats lemons?", punchline: "A sour puss!" },
  { id: "animal-077", category: "animals", setup: "Why don't crabs give to charity?", punchline: "Because they're shellfish!" },
  { id: "animal-078", category: "animals", setup: "What do you call a duck that steals?", punchline: "A robber ducky!" },
  { id: "animal-079", category: "animals", setup: "Why did the horse go behind the tree?", punchline: "To change his jockeys!" },
  { id: "animal-080", category: "animals", setup: "What do you call a dog in the summer?", punchline: "A hot dog!" },
  { id: "animal-081", category: "animals", setup: "Why did the whale cross the ocean?", punchline: "To get to the other tide!" },
  { id: "animal-082", category: "animals", setup: "What's a snake's favorite subject?", punchline: "Hisss-tory!" },
  { id: "animal-083", category: "animals", setup: "Why are teddy bears never hungry?", punchline: "Because they're always stuffed!" },
  { id: "animal-084", category: "animals", setup: "What do you call a pig doing karate?", punchline: "A pork chop!" },
  { id: "animal-085", category: "animals", setup: "Why did the owl say 'tweet'?", punchline: "Because he didn't give a hoot!" },
  { id: "animal-086", category: "animals", setup: "What do you call a cow that eats your grass?", punchline: "A lawn moo-er!" },
  { id: "animal-087", category: "animals", setup: "Why did the fish blush?", punchline: "Because it saw the ocean's bottom!" },
  { id: "animal-088", category: "animals", setup: "What's a cat's favorite button on a remote?", punchline: "Paws!" },
  { id: "animal-089", category: "animals", setup: "Why did the zebra go to jail?", punchline: "Because he was caught in black and white!" },
  { id: "animal-090", category: "animals", setup: "What do you call a dinosaur that asks a lot of questions?", punchline: "A query-saurus!" },
  { id: "animal-091", category: "animals", setup: "Why did the snail paint an S on his car?", punchline: "So people would say 'Look at that S car go!'" },
  { id: "animal-092", category: "animals", setup: "What do you call a grumpy cow?", punchline: "Moo-dy!" },
  { id: "animal-093", category: "animals", setup: "Why are spiders great web designers?", punchline: "They're really into networking!" },
  { id: "animal-094", category: "animals", setup: "What do you call a hippo that loves music?", punchline: "A hippo-beat!" },
  { id: "animal-095", category: "animals", setup: "Why did the butterfly go to the dance?", punchline: "Because it was a moth ball!" },
  { id: "animal-096", category: "animals", setup: "What do you call a dog that's a magician?", punchline: "A Labracadabrador!" },
  { id: "animal-097", category: "animals", setup: "Why don't ants get sick?", punchline: "Because they have little anty-bodies!" },
  { id: "animal-098", category: "animals", setup: "What do you call a fish that needs a lawyer?", punchline: "A gill-ty fish!" },
  { id: "animal-099", category: "animals", setup: "Why did the flamingo stand on one leg?", punchline: "Because if it lifted both legs, it would fall!" },
  { id: "animal-100", category: "animals", setup: "What do you call a goat in a boat?", punchline: "Billy the sailor!" },

  // ==========================================================================
  // KNOCK KNOCK (100+ jokes)
  // ==========================================================================
  { id: "knock-001", category: "knock-knock", setup: "Knock knock. Who's there? Boo. Boo who?", punchline: "Don't cry, it's just a joke!" },
  { id: "knock-002", category: "knock-knock", setup: "Knock knock. Who's there? Lettuce. Lettuce who?", punchline: "Lettuce in, it's cold out here!" },
  { id: "knock-003", category: "knock-knock", setup: "Knock knock. Who's there? Cow says. Cow says who?", punchline: "No silly, cow says MOOO!" },
  { id: "knock-004", category: "knock-knock", setup: "Knock knock. Who's there? Atch. Atch who?", punchline: "Bless you!" },
  { id: "knock-005", category: "knock-knock", setup: "Knock knock. Who's there? Tank. Tank who?", punchline: "You're welcome!" },
  { id: "knock-006", category: "knock-knock", setup: "Knock knock. Who's there? Banana. Banana who? (x3) Orange. Orange who?", punchline: "Orange you glad I didn't say banana?" },
  { id: "knock-007", category: "knock-knock", setup: "Knock knock. Who's there? Interrupting cow. Interrup—", punchline: "MOO!" },
  { id: "knock-008", category: "knock-knock", setup: "Knock knock. Who's there? Wooden shoe. Wooden shoe who?", punchline: "Wooden shoe like to hear another joke?" },
  { id: "knock-009", category: "knock-knock", setup: "Knock knock. Who's there? Nobel. Nobel who?", punchline: "Nobel, that's why I knocked!" },
  { id: "knock-010", category: "knock-knock", setup: "Knock knock. Who's there? Harry. Harry who?", punchline: "Harry up, it's cold out here!" },
  { id: "knock-011", category: "knock-knock", setup: "Knock knock. Who's there? Olive. Olive who?", punchline: "Olive you!" },
  { id: "knock-012", category: "knock-knock", setup: "Knock knock. Who's there? Police. Police who?", punchline: "Police let me in, it's cold!" },
  { id: "knock-013", category: "knock-knock", setup: "Knock knock. Who's there? Radio. Radio who?", punchline: "Radio not, here I come!" },
  { id: "knock-014", category: "knock-knock", setup: "Knock knock. Who's there? Spell. Spell who?", punchline: "W-H-O!" },
  { id: "knock-015", category: "knock-knock", setup: "Knock knock. Who's there? Cash. Cash who?", punchline: "No thanks, I prefer peanuts!" },
  { id: "knock-016", category: "knock-knock", setup: "Knock knock. Who's there? Donut. Donut who?", punchline: "Donut ask, it's a secret!" },
  { id: "knock-017", category: "knock-knock", setup: "Knock knock. Who's there? Honey bee. Honey bee who?", punchline: "Honey bee a dear and get me a drink!" },
  { id: "knock-018", category: "knock-knock", setup: "Knock knock. Who's there? Ice cream. Ice cream who?", punchline: "Ice cream if you don't let me in!" },
  { id: "knock-019", category: "knock-knock", setup: "Knock knock. Who's there? Luke. Luke who?", punchline: "Luke through the keyhole to see!" },
  { id: "knock-020", category: "knock-knock", setup: "Knock knock. Who's there? Who. Who who?", punchline: "Are you an owl?" },
  { id: "knock-021", category: "knock-knock", setup: "Knock knock. Who's there? Nana. Nana who?", punchline: "Nana your business!" },
  { id: "knock-022", category: "knock-knock", setup: "Knock knock. Who's there? Owls say. Owls say who?", punchline: "Yes, they do!" },
  { id: "knock-023", category: "knock-knock", setup: "Knock knock. Who's there? Needle. Needle who?", punchline: "Needle little help here!" },
  { id: "knock-024", category: "knock-knock", setup: "Knock knock. Who's there? Europe. Europe who?", punchline: "No, you're a poo!" },
  { id: "knock-025", category: "knock-knock", setup: "Knock knock. Who's there? Dishes. Dishes who?", punchline: "Dishes a really bad joke!" },
  { id: "knock-026", category: "knock-knock", setup: "Knock knock. Who's there? Water. Water who?", punchline: "Water you doing in my house?" },
  { id: "knock-027", category: "knock-knock", setup: "Knock knock. Who's there? Abby. Abby who?", punchline: "Abby birthday to you!" },
  { id: "knock-028", category: "knock-knock", setup: "Knock knock. Who's there? Cargo. Cargo who?", punchline: "Car go beep beep!" },
  { id: "knock-029", category: "knock-knock", setup: "Knock knock. Who's there? Mikey. Mikey who?", punchline: "Mikey doesn't fit in the lock!" },
  { id: "knock-030", category: "knock-knock", setup: "Knock knock. Who's there? Canoe. Canoe who?", punchline: "Canoe come out and play?" },
  { id: "knock-031", category: "knock-knock", setup: "Knock knock. Who's there? Cow. Cow who?", punchline: "No, cows moo, owls who!" },
  { id: "knock-032", category: "knock-knock", setup: "Knock knock. Who's there? Leaf. Leaf who?", punchline: "Leaf me alone!" },
  { id: "knock-033", category: "knock-knock", setup: "Knock knock. Who's there? Figs. Figs who?", punchline: "Figs the doorbell, it's broken!" },
  { id: "knock-034", category: "knock-knock", setup: "Knock knock. Who's there? Woo. Woo who?", punchline: "Don't get so excited, it's just a joke!" },
  { id: "knock-035", category: "knock-knock", setup: "Knock knock. Who's there? Annie. Annie who?", punchline: "Annie body home?" },
  { id: "knock-036", category: "knock-knock", setup: "Knock knock. Who's there? Chicken. Chicken who?", punchline: "Chicken your pockets, I think you lost your keys!" },
  { id: "knock-037", category: "knock-knock", setup: "Knock knock. Who's there? Kenya. Kenya who?", punchline: "Kenya feel the love tonight?" },
  { id: "knock-038", category: "knock-knock", setup: "Knock knock. Who's there? Howl. Howl who?", punchline: "Howl you know unless you open the door?" },
  { id: "knock-039", category: "knock-knock", setup: "Knock knock. Who's there? Cereal. Cereal who?", punchline: "Cereal pleasure to meet you!" },
  { id: "knock-040", category: "knock-knock", setup: "Knock knock. Who's there? Beets. Beets who?", punchline: "Beets me!" },
  { id: "knock-041", category: "knock-knock", setup: "Knock knock. Who's there? Snow. Snow who?", punchline: "Snow use, I forgot my name!" },
  { id: "knock-042", category: "knock-knock", setup: "Knock knock. Who's there? Butter. Butter who?", punchline: "Butter let me in or else!" },
  { id: "knock-043", category: "knock-knock", setup: "Knock knock. Who's there? Justin. Justin who?", punchline: "Justin time for dinner!" },
  { id: "knock-044", category: "knock-knock", setup: "Knock knock. Who's there? Dwayne. Dwayne who?", punchline: "Dwayne the bathtub, I'm dwowning!" },
  { id: "knock-045", category: "knock-knock", setup: "Knock knock. Who's there? Iva. Iva who?", punchline: "I've a sore hand from knocking!" },
  { id: "knock-046", category: "knock-knock", setup: "Knock knock. Who's there? Otto. Otto who?", punchline: "Otto know what's taking you so long!" },
  { id: "knock-047", category: "knock-knock", setup: "Knock knock. Who's there? Etch. Etch who?", punchline: "Bless you!" },
  { id: "knock-048", category: "knock-knock", setup: "Knock knock. Who's there? Howard. Howard who?", punchline: "Howard you like to let me in?" },
  { id: "knock-049", category: "knock-knock", setup: "Knock knock. Who's there? Dozen. Dozen who?", punchline: "Dozen anyone want to let me in?" },
  { id: "knock-050", category: "knock-knock", setup: "Knock knock. Who's there? Yah. Yah who?", punchline: "Wow, you're excited to see me!" },
  { id: "knock-051", category: "knock-knock", setup: "Knock knock. Who's there? Alpaca. Alpaca who?", punchline: "Alpaca the suitcase, you load the car!" },
  { id: "knock-052", category: "knock-knock", setup: "Knock knock. Who's there? Will. Will who?", punchline: "Will you please let me in?" },
  { id: "knock-053", category: "knock-knock", setup: "Knock knock. Who's there? Art. Art who?", punchline: "R2-D2!" },
  { id: "knock-054", category: "knock-knock", setup: "Knock knock. Who's there? Stopwatch. Stopwatch who?", punchline: "Stopwatch you're doing and open the door!" },
  { id: "knock-055", category: "knock-knock", setup: "Knock knock. Who's there? Norma Lee. Norma Lee who?", punchline: "Norma Lee I don't knock on doors, but I had to see you!" },
  { id: "knock-056", category: "knock-knock", setup: "Knock knock. Who's there? Ketchup. Ketchup who?", punchline: "Ketchup with me and I'll tell you!" },
  { id: "knock-057", category: "knock-knock", setup: "Knock knock. Who's there? Gladys. Gladys who?", punchline: "Gladys the weekend, aren't you?" },
  { id: "knock-058", category: "knock-knock", setup: "Knock knock. Who's there? Broken pencil. Broken pencil who?", punchline: "Never mind, it's pointless!" },
  { id: "knock-059", category: "knock-knock", setup: "Knock knock. Who's there? Cook. Cook who?", punchline: "What? Are you calling me crazy?" },
  { id: "knock-060", category: "knock-knock", setup: "Knock knock. Who's there? Ya. Ya who?", punchline: "I'm excited to see you too!" },
  { id: "knock-061", category: "knock-knock", setup: "Knock knock. Who's there? A little old lady. A little old lady who?", punchline: "I didn't know you could yodel!" },
  { id: "knock-062", category: "knock-knock", setup: "Knock knock. Who's there? Althea. Althea who?", punchline: "Althea later, alligator!" },
  { id: "knock-063", category: "knock-knock", setup: "Knock knock. Who's there? Wa. Wa who?", punchline: "What are you so excited about?" },
  { id: "knock-064", category: "knock-knock", setup: "Knock knock. Who's there? Repeat. Repeat who?", punchline: "Who who who who who!" },
  { id: "knock-065", category: "knock-knock", setup: "Knock knock. Who's there? Tennis. Tennis who?", punchline: "Tennis five plus five!" },
  { id: "knock-066", category: "knock-knock", setup: "Knock knock. Who's there? Oink oink. Oink oink who?", punchline: "Make up your mind, are you a pig or an owl?" },
  { id: "knock-067", category: "knock-knock", setup: "Knock knock. Who's there? Bea. Bea who?", punchline: "Bea-cause I said so!" },
  { id: "knock-068", category: "knock-knock", setup: "Knock knock. Who's there? Says. Says who?", punchline: "Says me, that's who!" },
  { id: "knock-069", category: "knock-knock", setup: "Knock knock. Who's there? Amish. Amish who?", punchline: "Aww, I miss you too!" },
  { id: "knock-070", category: "knock-knock", setup: "Knock knock. Who's there? Boo. Boo who?", punchline: "Why are you crying?" },
  { id: "knock-071", category: "knock-knock", setup: "Knock knock. Who's there? Hatch. Hatch who?", punchline: "Bless you!" },
  { id: "knock-072", category: "knock-knock", setup: "Knock knock. Who's there? Anita. Anita who?", punchline: "Anita to borrow a pencil!" },
  { id: "knock-073", category: "knock-knock", setup: "Knock knock. Who's there? Alex. Alex who?", punchline: "Alex-plain later, let me in!" },
  { id: "knock-074", category: "knock-knock", setup: "Knock knock. Who's there? Arch. Arch who?", punchline: "Bless you!" },
  { id: "knock-075", category: "knock-knock", setup: "Knock knock. Who's there? Wooden. Wooden who?", punchline: "Wooden you like to know!" },
  { id: "knock-076", category: "knock-knock", setup: "Knock knock. Who's there? Avenue. Avenue who?", punchline: "Avenue knocked on this door before?" },
  { id: "knock-077", category: "knock-knock", setup: "Knock knock. Who's there? Henrietta. Henrietta who?", punchline: "Henrietta worm that was in his apple!" },
  { id: "knock-078", category: "knock-knock", setup: "Knock knock. Who's there? Wendy. Wendy who?", punchline: "Wendy wind blows, the cradle will rock!" },
  { id: "knock-079", category: "knock-knock", setup: "Knock knock. Who's there? Irish. Irish who?", punchline: "Irish you a happy birthday!" },
  { id: "knock-080", category: "knock-knock", setup: "Knock knock. Who's there? Cows go. Cows go who?", punchline: "No silly, cows go MOO!" },
  { id: "knock-081", category: "knock-knock", setup: "Knock knock. Who's there? Frank. Frank who?", punchline: "Frank you for being my friend!" },
  { id: "knock-082", category: "knock-knock", setup: "Knock knock. Who's there? Scold. Scold who?", punchline: "Scold outside, let me in!" },
  { id: "knock-083", category: "knock-knock", setup: "Knock knock. Who's there? Wanda. Wanda who?", punchline: "Wanda hang out with me?" },
  { id: "knock-084", category: "knock-knock", setup: "Knock knock. Who's there? Yukon. Yukon who?", punchline: "Yukon say that again!" },
  { id: "knock-085", category: "knock-knock", setup: "Knock knock. Who's there? Ada. Ada who?", punchline: "Ada burger for lunch!" },
  { id: "knock-086", category: "knock-knock", setup: "Knock knock. Who's there? Ice cream soda. Ice cream soda who?", punchline: "Ice cream soda whole world can hear!" },
  { id: "knock-087", category: "knock-knock", setup: "Knock knock. Who's there? Interrupting sloth. Interrupting sl—", punchline: "...o...t...h!" },
  { id: "knock-088", category: "knock-knock", setup: "Knock knock. Who's there? Banana. Banana who?", punchline: "Banana split so ice creamed!" },
  { id: "knock-089", category: "knock-knock", setup: "Knock knock. Who's there? Ben. Ben who?", punchline: "Ben knocking for 10 minutes!" },
  { id: "knock-090", category: "knock-knock", setup: "Knock knock. Who's there? Toad. Toad who?", punchline: "I toad you already!" },
  { id: "knock-091", category: "knock-knock", setup: "Knock knock. Who's there? Maida. Maida who?", punchline: "Maida mistake with this joke!" },
  { id: "knock-092", category: "knock-knock", setup: "Knock knock. Who's there? Aida. Aida who?", punchline: "Aida lot of candy and now I feel sick!" },
  { id: "knock-093", category: "knock-knock", setup: "Knock knock. Who's there? Theodore. Theodore who?", punchline: "Theodore wasn't open so I knocked!" },
  { id: "knock-094", category: "knock-knock", setup: "Knock knock. Who's there? Ivana. Ivana who?", punchline: "Ivana come in!" },
  { id: "knock-095", category: "knock-knock", setup: "Knock knock. Who's there? Icy. Icy who?", punchline: "Icy you looking at me!" },
  { id: "knock-096", category: "knock-knock", setup: "Knock knock. Who's there? Turnip. Turnip who?", punchline: "Turnip the volume, it's my favorite song!" },
  { id: "knock-097", category: "knock-knock", setup: "Knock knock. Who's there? Hugo. Hugo who?", punchline: "Hugo first, I'm right behind you!" },
  { id: "knock-098", category: "knock-knock", setup: "Knock knock. Who's there? Wire. Wire who?", punchline: "Wire you asking so many questions?" },
  { id: "knock-099", category: "knock-knock", setup: "Knock knock. Who's there? Razor. Razor who?", punchline: "Razor hand if you like jokes!" },
  { id: "knock-100", category: "knock-knock", setup: "Knock knock. Who's there? Iowa. Iowa who?", punchline: "Iowa you a favor!" },

  // ==========================================================================
  // SCHOOL (100+ jokes)
  // ==========================================================================
  { id: "school-001", category: "school", setup: "Why did the student eat his homework?", punchline: "Because his teacher told him it was a piece of cake!" },
  { id: "school-002", category: "school", setup: "What's a math teacher's favorite place to vacation?", punchline: "Times Square!" },
  { id: "school-003", category: "school", setup: "Why did the music teacher need a ladder?", punchline: "To reach the high notes!" },
  { id: "school-004", category: "school", setup: "What do you call a number that can't sit still?", punchline: "A roamin' numeral!" },
  { id: "school-005", category: "school", setup: "Why was the math book sad?", punchline: "Because it had too many problems!" },
  { id: "school-006", category: "school", setup: "What's a snake's favorite subject?", punchline: "Hisssstory!" },
  { id: "school-007", category: "school", setup: "Why did the kid bring a ladder to school?", punchline: "Because he wanted to go to high school!" },
  { id: "school-008", category: "school", setup: "What do elves learn in school?", punchline: "The elf-abet!" },
  { id: "school-009", category: "school", setup: "Why do calculators make great friends?", punchline: "Because you can always count on them!" },
  { id: "school-010", category: "school", setup: "What did the pencil say to the paper?", punchline: "I dot my i's on you!" },
  { id: "school-011", category: "school", setup: "Why did the broom get a bad grade?", punchline: "Because it was always sweeping during class!" },
  { id: "school-012", category: "school", setup: "What's a witch's favorite subject?", punchline: "Spelling!" },
  { id: "school-013", category: "school", setup: "Why did the clock go to the principal's office?", punchline: "For tocking too much!" },
  { id: "school-014", category: "school", setup: "What do you get when you cross a teacher with a vampire?", punchline: "Lots of blood tests!" },
  { id: "school-015", category: "school", setup: "Why did the geometry book look so sad?", punchline: "Because it had too many problems!" },
  { id: "school-016", category: "school", setup: "What's a teacher's favorite nation?", punchline: "Expla-nation!" },
  { id: "school-017", category: "school", setup: "Why did the student drown?", punchline: "All her grades were below C-level!" },
  { id: "school-018", category: "school", setup: "What do you call a math teacher who can do magic?", punchline: "A mathemagician!" },
  { id: "school-019", category: "school", setup: "Why did the student bring scissors to school?", punchline: "To cut class!" },
  { id: "school-020", category: "school", setup: "What's the king of all school supplies?", punchline: "The ruler!" },
  { id: "school-021", category: "school", setup: "Why did the music note go to the doctor?", punchline: "Because it was feeling flat!" },
  { id: "school-022", category: "school", setup: "What did the calculator say to the student?", punchline: "You can count on me!" },
  { id: "school-023", category: "school", setup: "Why did the student fail the history test?", punchline: "Because all the answers were in the past!" },
  { id: "school-024", category: "school", setup: "What's a pirate's favorite letter?", punchline: "You'd think it's R, but it's the C they love!" },
  { id: "school-025", category: "school", setup: "Why was 6 afraid of 7?", punchline: "Because 7, 8, 9!" },
  { id: "school-026", category: "school", setup: "What did the pen say to the pencil?", punchline: "What's your point?" },
  { id: "school-027", category: "school", setup: "Why do scientists like nitrates?", punchline: "Because they're cheaper than day rates!" },
  { id: "school-028", category: "school", setup: "What do you call a teacher without students?", punchline: "Happy!" },
  { id: "school-029", category: "school", setup: "Why did the nose not want to go to school?", punchline: "Because it was tired of being picked on!" },
  { id: "school-030", category: "school", setup: "What's the best place to grow flowers in school?", punchline: "In kinder-garden!" },
  { id: "school-031", category: "school", setup: "Why did the echo get detention?", punchline: "Because it kept talking back!" },
  { id: "school-032", category: "school", setup: "What do you call a dinosaur that's a good student?", punchline: "A dino-scholar!" },
  { id: "school-033", category: "school", setup: "Why did the bicycle fall asleep in class?", punchline: "Because it was two-tired!" },
  { id: "school-034", category: "school", setup: "What's a math teacher's favorite dessert?", punchline: "Pi!" },
  { id: "school-035", category: "school", setup: "Why do magicians do well in school?", punchline: "Because they're good at trick questions!" },
  { id: "school-036", category: "school", setup: "What did the triangle say to the circle?", punchline: "You're pointless!" },
  { id: "school-037", category: "school", setup: "Why did the report card go to therapy?", punchline: "It had too many issues!" },
  { id: "school-038", category: "school", setup: "What's an astronaut's favorite key on the keyboard?", punchline: "The space bar!" },
  { id: "school-039", category: "school", setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!" },
  { id: "school-040", category: "school", setup: "What do librarians take fishing?", punchline: "Bookworms!" },
  { id: "school-041", category: "school", setup: "Why was the equal sign so humble?", punchline: "Because it knew it wasn't less than or greater than anyone!" },
  { id: "school-042", category: "school", setup: "What's a chemistry teacher's favorite thing to eat?", punchline: "Barium, Cobalt, and Nitrogen - BaCoN!" },
  { id: "school-043", category: "school", setup: "Why did the student throw a clock out the window?", punchline: "To see time fly!" },
  { id: "school-044", category: "school", setup: "What kind of tree fits in your hand?", punchline: "A palm tree!" },
  { id: "school-045", category: "school", setup: "Why did the teacher wear sunglasses?", punchline: "Because her students were so bright!" },
  { id: "school-046", category: "school", setup: "What's the smartest bug?", punchline: "A spelling bee!" },
  { id: "school-047", category: "school", setup: "Why did the eraser go to the school nurse?", punchline: "Because it made too many mistakes!" },
  { id: "school-048", category: "school", setup: "What do you call an educated tube?", punchline: "A graduated cylinder!" },
  { id: "school-049", category: "school", setup: "Why did the student bring a flashlight to school?", punchline: "Because she was a bright student!" },
  { id: "school-050", category: "school", setup: "What's a ghost's favorite class?", punchline: "BOO-logy!" },
  { id: "school-051", category: "school", setup: "Why did the textbook feel lonely?", punchline: "Because its friends were all in different classes!" },
  { id: "school-052", category: "school", setup: "What do you call a group of musical whales?", punchline: "An orca-stra!" },
  { id: "school-053", category: "school", setup: "Why did the gym teacher go to the bank?", punchline: "To get his quarterback!" },
  { id: "school-054", category: "school", setup: "What did the paper say to the pencil?", punchline: "Write on!" },
  { id: "school-055", category: "school", setup: "Why did the M&M go to school?", punchline: "Because it wanted to be a Smartie!" },
  { id: "school-056", category: "school", setup: "What's a frog's favorite class?", punchline: "Croak-istry!" },
  { id: "school-057", category: "school", setup: "Why did the student bring a mirror to class?", punchline: "So she could reflect on her answers!" },
  { id: "school-058", category: "school", setup: "What do you call a fish that knows everything?", punchline: "A brain sturgeon!" },
  { id: "school-059", category: "school", setup: "Why was the obtuse angle upset?", punchline: "Because it was never right!" },
  { id: "school-060", category: "school", setup: "What did 0 say to 8?", punchline: "Nice belt!" },
  { id: "school-061", category: "school", setup: "Why did the invisible man turn down the teaching job?", punchline: "He couldn't see himself doing it!" },
  { id: "school-062", category: "school", setup: "What's a dog's favorite subject?", punchline: "Barkaeology!" },
  { id: "school-063", category: "school", setup: "Why did the atom cross the road?", punchline: "Because it was time to split!" },
  { id: "school-064", category: "school", setup: "What do you call a dinosaur that's sleeping?", punchline: "A dino-snore!" },
  { id: "school-065", category: "school", setup: "Why did the class clown fail the test?", punchline: "Because all his answers were jokes!" },
  { id: "school-066", category: "school", setup: "What's the most musical bone?", punchline: "The trom-bone!" },
  { id: "school-067", category: "school", setup: "Why couldn't the angle get a loan?", punchline: "His parents wouldn't co-sine!" },
  { id: "school-068", category: "school", setup: "What do you call a bear that's stuck in the rain?", punchline: "A drizzly bear!" },
  { id: "school-069", category: "school", setup: "Why do birds fly south for school?", punchline: "Because it's too far to walk!" },
  { id: "school-070", category: "school", setup: "What's a cat's favorite school subject?", punchline: "MEW-sic!" },
  { id: "school-071", category: "school", setup: "Why did the smartphone go to school?", punchline: "To become smarter!" },
  { id: "school-072", category: "school", setup: "What's a balloon's least favorite class?", punchline: "Pop quiz!" },
  { id: "school-073", category: "school", setup: "Why did the light bulb do well in school?", punchline: "Because it was so bright!" },
  { id: "school-074", category: "school", setup: "What did one book say to the other?", punchline: "I just wanted to see if we're on the same page!" },
  { id: "school-075", category: "school", setup: "Why do plants hate math?", punchline: "Because it gives them square roots!" },
  { id: "school-076", category: "school", setup: "What's a volcano's favorite class?", punchline: "Geography - they really dig it!" },
  { id: "school-077", category: "school", setup: "Why did the computer go to the doctor?", punchline: "Because it had a virus!" },
  { id: "school-078", category: "school", setup: "What do you call a sleeping dinosaur?", punchline: "A dino-snore!" },
  { id: "school-079", category: "school", setup: "Why was the fraction nervous about marrying the decimal?", punchline: "Because she would have to convert!" },
  { id: "school-080", category: "school", setup: "What do you call a can opener that doesn't work?", punchline: "A can't opener!" },
  { id: "school-081", category: "school", setup: "Why did the student write on the window?", punchline: "The teacher told him to make it clear!" },
  { id: "school-082", category: "school", setup: "What did the science book say to the math book?", punchline: "You've got problems!" },
  { id: "school-083", category: "school", setup: "Why did the period break up with the exclamation point?", punchline: "Too much drama!" },
  { id: "school-084", category: "school", setup: "What do you call a cow that plays a musical instrument?", punchline: "A moo-sician!" },
  { id: "school-085", category: "school", setup: "Why did the verb feel so tired?", punchline: "Because it was always in action!" },
  { id: "school-086", category: "school", setup: "What's a duck's favorite class?", punchline: "Quack-ulus!" },
  { id: "school-087", category: "school", setup: "Why did the music teacher go to jail?", punchline: "For getting in treble!" },
  { id: "school-088", category: "school", setup: "What did the baby corn say to the mama corn?", punchline: "Where's pop corn?" },
  { id: "school-089", category: "school", setup: "Why did the notebook go to therapy?", punchline: "It had too many issues!" },
  { id: "school-090", category: "school", setup: "What's a cow's favorite subject?", punchline: "Moo-sic!" },
  { id: "school-091", category: "school", setup: "Why did the crayon get in trouble?", punchline: "It kept drawing attention to itself!" },
  { id: "school-092", category: "school", setup: "What's the difference between a teacher and a train?", punchline: "A teacher says 'Spit out your gum' and a train says 'Chew chew!'" },
  { id: "school-093", category: "school", setup: "Why did the rubber band go to school?", punchline: "To learn how to stretch its mind!" },
  { id: "school-094", category: "school", setup: "What do you call cheese that isn't yours?", punchline: "Nacho cheese!" },
  { id: "school-095", category: "school", setup: "Why did the teacher jump in the pool?", punchline: "To test the water!" },
  { id: "school-096", category: "school", setup: "What's a cloud's favorite subject?", punchline: "Mist-ory!" },
  { id: "school-097", category: "school", setup: "Why did the school cook quit?", punchline: "Because the students kept telling her to cut the beans!" },
  { id: "school-098", category: "school", setup: "What do you call an alligator in a vest at school?", punchline: "An investigator!" },
  { id: "school-099", category: "school", setup: "Why did the egg go to school?", punchline: "To get egg-ucated!" },
  { id: "school-100", category: "school", setup: "What's a tree's least favorite month?", punchline: "Sep-timber!" },

  // ==========================================================================
  // SILLY (100+ jokes)
  // ==========================================================================
  { id: "silly-001", category: "silly", setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!" },
  { id: "silly-002", category: "silly", setup: "What do you call a fake noodle?", punchline: "An impasta!" },
  { id: "silly-003", category: "silly", setup: "Why can't you give Elsa a balloon?", punchline: "Because she'll let it go!" },
  { id: "silly-004", category: "silly", setup: "What did the ocean say to the beach?", punchline: "Nothing, it just waved!" },
  { id: "silly-005", category: "silly", setup: "Why did the scarecrow win an award?", punchline: "Because he was outstanding in his field!" },
  { id: "silly-006", category: "silly", setup: "What do you call a boomerang that doesn't come back?", punchline: "A stick!" },
  { id: "silly-007", category: "silly", setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one!" },
  { id: "silly-008", category: "silly", setup: "What did the left eye say to the right eye?", punchline: "Between you and me, something smells!" },
  { id: "silly-009", category: "silly", setup: "Why can't your nose be 12 inches long?", punchline: "Because then it would be a foot!" },
  { id: "silly-010", category: "silly", setup: "What do you call a dinosaur that crashes their car?", punchline: "Tyrannosaurus Wrecks!" },
  { id: "silly-011", category: "silly", setup: "Why did the bicycle fall over?", punchline: "Because it was two-tired!" },
  { id: "silly-012", category: "silly", setup: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman!" },
  { id: "silly-013", category: "silly", setup: "Why did the tomato blush?", punchline: "Because it saw the salad dressing!" },
  { id: "silly-014", category: "silly", setup: "What do you call a belt made of watches?", punchline: "A waist of time!" },
  { id: "silly-015", category: "silly", setup: "Why did the stadium get hot?", punchline: "Because all the fans left!" },
  { id: "silly-016", category: "silly", setup: "What do you call a sleeping dinosaur?", punchline: "A dino-snore!" },
  { id: "silly-017", category: "silly", setup: "Why did the cookie go to the hospital?", punchline: "Because it was feeling crummy!" },
  { id: "silly-018", category: "silly", setup: "What's brown and sticky?", punchline: "A stick!" },
  { id: "silly-019", category: "silly", setup: "Why did the picture go to jail?", punchline: "Because it was framed!" },
  { id: "silly-020", category: "silly", setup: "What do you call a parade of rabbits hopping backwards?", punchline: "A receding hare-line!" },
  { id: "silly-021", category: "silly", setup: "Why did the bank robber take a bath?", punchline: "To make a clean getaway!" },
  { id: "silly-022", category: "silly", setup: "What do you call a bear with no ears?", punchline: "B!" },
  { id: "silly-023", category: "silly", setup: "Why don't eggs tell jokes?", punchline: "They'd crack each other up!" },
  { id: "silly-024", category: "silly", setup: "What do you call a lazy kangaroo?", punchline: "A pouch potato!" },
  { id: "silly-025", category: "silly", setup: "Why did the gym close down?", punchline: "It just didn't work out!" },
  { id: "silly-026", category: "silly", setup: "What has ears but can't hear?", punchline: "A cornfield!" },
  { id: "silly-027", category: "silly", setup: "Why did the skeleton go to the party alone?", punchline: "Because he had no body to go with!" },
  { id: "silly-028", category: "silly", setup: "What do you call a pig that does karate?", punchline: "A pork chop!" },
  { id: "silly-029", category: "silly", setup: "Why can't you hear a pterodactyl using the bathroom?", punchline: "Because the 'p' is silent!" },
  { id: "silly-030", category: "silly", setup: "What do you call a fish wearing a bowtie?", punchline: "So-fish-ticated!" },
  { id: "silly-031", category: "silly", setup: "Why did the invisible man turn down the job?", punchline: "He couldn't see himself doing it!" },
  { id: "silly-032", category: "silly", setup: "What do you call a magic dog?", punchline: "A Labracadabrador!" },
  { id: "silly-033", category: "silly", setup: "Why did the melon jump into the lake?", punchline: "Because it wanted to be a watermelon!" },
  { id: "silly-034", category: "silly", setup: "What do you call a deer with no eyes?", punchline: "No idea!" },
  { id: "silly-035", category: "silly", setup: "Why did the football coach go to the bank?", punchline: "To get his quarterback!" },
  { id: "silly-036", category: "silly", setup: "What do you call a ghost's true love?", punchline: "A ghoul-friend!" },
  { id: "silly-037", category: "silly", setup: "Why did the baker stop making donuts?", punchline: "Because he got tired of the hole thing!" },
  { id: "silly-038", category: "silly", setup: "What's orange and sounds like a parrot?", punchline: "A carrot!" },
  { id: "silly-039", category: "silly", setup: "Why did the vampire read the newspaper?", punchline: "Because he heard it had great circulation!" },
  { id: "silly-040", category: "silly", setup: "What do you call a cow with two legs?", punchline: "Lean beef!" },
  { id: "silly-041", category: "silly", setup: "Why did the coffee call the police?", punchline: "It got mugged!" },
  { id: "silly-042", category: "silly", setup: "What has hands but can't clap?", punchline: "A clock!" },
  { id: "silly-043", category: "silly", setup: "Why did the banana go to the doctor?", punchline: "Because it wasn't peeling well!" },
  { id: "silly-044", category: "silly", setup: "What do you call a story about a broken pencil?", punchline: "Pointless!" },
  { id: "silly-045", category: "silly", setup: "Why did the astronaut break up with his girlfriend?", punchline: "Because he needed more space!" },
  { id: "silly-046", category: "silly", setup: "What do you call a sleeping bull?", punchline: "A bulldozer!" },
  { id: "silly-047", category: "silly", setup: "Why did the tree go to the dentist?", punchline: "To get a root canal!" },
  { id: "silly-048", category: "silly", setup: "What do you call a shoe made of a banana?", punchline: "A slipper!" },
  { id: "silly-049", category: "silly", setup: "Why don't mountains get cold?", punchline: "They wear snow caps!" },
  { id: "silly-050", category: "silly", setup: "What do you call a dinosaur that is a good singer?", punchline: "A sing-a-saurus!" },
  { id: "silly-051", category: "silly", setup: "Why did the moon skip dinner?", punchline: "Because it was full!" },
  { id: "silly-052", category: "silly", setup: "What do clouds wear under their clothes?", punchline: "Thunderwear!" },
  { id: "silly-053", category: "silly", setup: "Why did the orange stop rolling down the hill?", punchline: "It ran out of juice!" },
  { id: "silly-054", category: "silly", setup: "What do you call a funny mountain?", punchline: "Hill-arious!" },
  { id: "silly-055", category: "silly", setup: "Why did the skeleton not go to the dance?", punchline: "He had no body to dance with!" },
  { id: "silly-056", category: "silly", setup: "What's a tornado's favorite game?", punchline: "Twister!" },
  { id: "silly-057", category: "silly", setup: "Why did the robot go on vacation?", punchline: "To recharge its batteries!" },
  { id: "silly-058", category: "silly", setup: "What do you call a train that sneezes?", punchline: "Achoo-choo train!" },
  { id: "silly-059", category: "silly", setup: "Why did the lightbulb fail the test?", punchline: "It wasn't too bright!" },
  { id: "silly-060", category: "silly", setup: "What do you call a cold dog?", punchline: "A chili dog!" },
  { id: "silly-061", category: "silly", setup: "Why did the sun go to school?", punchline: "To get a little brighter!" },
  { id: "silly-062", category: "silly", setup: "What do you call a bee that can't make up its mind?", punchline: "A maybe!" },
  { id: "silly-063", category: "silly", setup: "Why did the mummy go to school?", punchline: "To get wrapped up in learning!" },
  { id: "silly-064", category: "silly", setup: "What do you call a sleeping pizza?", punchline: "A piZZZZza!" },
  { id: "silly-065", category: "silly", setup: "Why did the broom get a promotion?", punchline: "It swept the competition!" },
  { id: "silly-066", category: "silly", setup: "What do you call a monkey that loves chips?", punchline: "A chipmunk!" },
  { id: "silly-067", category: "silly", setup: "Why did the phone wear glasses?", punchline: "Because it lost its contacts!" },
  { id: "silly-068", category: "silly", setup: "What do you call a fish with no eyes?", punchline: "Fsh!" },
  { id: "silly-069", category: "silly", setup: "Why did the mushroom go to the party?", punchline: "Because he was a fungi!" },
  { id: "silly-070", category: "silly", setup: "What do you call a pig that knows karate?", punchline: "Pork chop!" },
  { id: "silly-071", category: "silly", setup: "Why did the lemon stop in the middle of the road?", punchline: "It ran out of juice!" },
  { id: "silly-072", category: "silly", setup: "What do you call a dinosaur fart?", punchline: "A blast from the past!" },
  { id: "silly-073", category: "silly", setup: "Why did the mirror feel happy?", punchline: "Because it reflected on good times!" },
  { id: "silly-074", category: "silly", setup: "What do you call a cheese that isn't yours?", punchline: "Nacho cheese!" },
  { id: "silly-075", category: "silly", setup: "Why did the paper go to the gym?", punchline: "To get ripped!" },
  { id: "silly-076", category: "silly", setup: "What do you call a snowman in the summer?", punchline: "A puddle!" },
  { id: "silly-077", category: "silly", setup: "Why did the balloon pop?", punchline: "It just couldn't take the pressure!" },
  { id: "silly-078", category: "silly", setup: "What do you call a lazy baby kangaroo?", punchline: "A pouch potato!" },
  { id: "silly-079", category: "silly", setup: "Why did the computer catch a cold?", punchline: "It left its Windows open!" },
  { id: "silly-080", category: "silly", setup: "What do you call a sheep with no legs?", punchline: "A cloud!" },
  { id: "silly-081", category: "silly", setup: "Why did the math book look so sad?", punchline: "Because it had so many problems!" },
  { id: "silly-082", category: "silly", setup: "What do you call a pile of cats?", punchline: "A meow-ntain!" },
  { id: "silly-083", category: "silly", setup: "Why did the lamp break up with the light switch?", punchline: "It was too controlling!" },
  { id: "silly-084", category: "silly", setup: "What do you call a grumpy cow?", punchline: "Moo-dy!" },
  { id: "silly-085", category: "silly", setup: "Why did the quarter cry?", punchline: "Because it was too common for its own cents!" },
  { id: "silly-086", category: "silly", setup: "What do you call a lazy eyeball?", punchline: "Eye-dle!" },
  { id: "silly-087", category: "silly", setup: "Why did the calendar feel popular?", punchline: "It had so many dates!" },
  { id: "silly-088", category: "silly", setup: "What do you call a funny pepper?", punchline: "A pepper-oni!" },
  { id: "silly-089", category: "silly", setup: "Why did the music teacher break up with her fiancé?", punchline: "He was too flat!" },
  { id: "silly-090", category: "silly", setup: "What do you call a fake stone?", punchline: "A sham-rock!" },
  { id: "silly-091", category: "silly", setup: "Why did the teddy bear say no to dessert?", punchline: "She was already stuffed!" },
  { id: "silly-092", category: "silly", setup: "What do you call a sleeping dinosaur?", punchline: "A dino-snore!" },
  { id: "silly-093", category: "silly", setup: "Why did the sock go to therapy?", punchline: "It lost its sole mate!" },
  { id: "silly-094", category: "silly", setup: "What do you call a nosy pepper?", punchline: "Jalapeño business!" },
  { id: "silly-095", category: "silly", setup: "Why did the rope break up with the string?", punchline: "It was too attached!" },
  { id: "silly-096", category: "silly", setup: "What do you call a sad strawberry?", punchline: "A blueberry!" },
  { id: "silly-097", category: "silly", setup: "Why did the pillow go to the doctor?", punchline: "It was feeling down!" },
  { id: "silly-098", category: "silly", setup: "What do you call a running nose?", punchline: "A marathon snot!" },
  { id: "silly-099", category: "silly", setup: "Why did the clock get detention?", punchline: "It tocked too much!" },
  { id: "silly-100", category: "silly", setup: "What do you call a broken clock?", punchline: "Still right twice a day!" },

  // ==========================================================================
  // FOOD (100+ jokes)
  // ==========================================================================
  { id: "food-001", category: "food", setup: "Why did the banana go to the doctor?", punchline: "Because it wasn't peeling well!" },
  { id: "food-002", category: "food", setup: "What do you call cheese that isn't yours?", punchline: "Nacho cheese!" },
  { id: "food-003", category: "food", setup: "Why did the cookie go to the hospital?", punchline: "Because it was feeling crummy!" },
  { id: "food-004", category: "food", setup: "What do you call a sad strawberry?", punchline: "A blueberry!" },
  { id: "food-005", category: "food", setup: "What does a lemon say when it answers the phone?", punchline: "Yellow!" },
  { id: "food-006", category: "food", setup: "Why did the tomato turn red?", punchline: "Because it saw the salad dressing!" },
  { id: "food-007", category: "food", setup: "What do you call a peanut in a spacesuit?", punchline: "An astronut!" },
  { id: "food-008", category: "food", setup: "Why don't eggs tell jokes?", punchline: "They'd crack each other up!" },
  { id: "food-009", category: "food", setup: "What did the grape say when it got stepped on?", punchline: "Nothing, it just let out a little wine!" },
  { id: "food-010", category: "food", setup: "Why did the bread break up with the margarine?", punchline: "For a butter lover!" },
  { id: "food-011", category: "food", setup: "What do you call a fake noodle?", punchline: "An impasta!" },
  { id: "food-012", category: "food", setup: "Why did the orange lose the race?", punchline: "It ran out of juice!" },
  { id: "food-013", category: "food", setup: "What did the hungry computer eat?", punchline: "Chips!" },
  { id: "food-014", category: "food", setup: "Why did the jelly bean go to school?", punchline: "To become a Smartie!" },
  { id: "food-015", category: "food", setup: "What's a ghost's favorite fruit?", punchline: "Boo-berries!" },
  { id: "food-016", category: "food", setup: "Why did the coffee go to the police?", punchline: "It got mugged!" },
  { id: "food-017", category: "food", setup: "What do you call a sleeping pizza?", punchline: "A piZZZZa!" },
  { id: "food-018", category: "food", setup: "Why did the pancake go to therapy?", punchline: "It had too many layers!" },
  { id: "food-019", category: "food", setup: "What do you call a lazy burger?", punchline: "A couch patty!" },
  { id: "food-020", category: "food", setup: "Why did the lettuce win the race?", punchline: "Because it was a head!" },
  { id: "food-021", category: "food", setup: "What do you call a happy onion?", punchline: "An onion-ring of joy!" },
  { id: "food-022", category: "food", setup: "Why did the apple go to the dentist?", punchline: "To get a filling!" },
  { id: "food-023", category: "food", setup: "What's a vampire's favorite fruit?", punchline: "A neck-tarine!" },
  { id: "food-024", category: "food", setup: "Why did the cucumber call 911?", punchline: "Because it was in a pickle!" },
  { id: "food-025", category: "food", setup: "What did one plate say to the other plate?", punchline: "Dinner is on me!" },
  { id: "food-026", category: "food", setup: "Why did the mushroom go to the party?", punchline: "Because he's a fun-gi!" },
  { id: "food-027", category: "food", setup: "What do you call a cow that eats your grass?", punchline: "A lawn moo-er!" },
  { id: "food-028", category: "food", setup: "Why did the baker stop making donuts?", punchline: "He got tired of the hole thing!" },
  { id: "food-029", category: "food", setup: "What's the best thing to put into a pie?", punchline: "Your teeth!" },
  { id: "food-030", category: "food", setup: "Why did the chicken cross the road?", punchline: "To prove he wasn't chicken!" },
  { id: "food-031", category: "food", setup: "What do you call a hot dog with nothing inside?", punchline: "A hollow-weenie!" },
  { id: "food-032", category: "food", setup: "Why did the soup break up with the spoon?", punchline: "It was too stirring!" },
  { id: "food-033", category: "food", setup: "What do elves eat for breakfast?", punchline: "Frosted Flakes!" },
  { id: "food-034", category: "food", setup: "Why did the chef quit?", punchline: "He ran out of thyme!" },
  { id: "food-035", category: "food", setup: "What's a cat's favorite candy?", punchline: "Kit-Kats!" },
  { id: "food-036", category: "food", setup: "Why did the gum cross the road?", punchline: "It was stuck to the chicken's foot!" },
  { id: "food-037", category: "food", setup: "What do you call a frozen potato?", punchline: "A tater-tot!" },
  { id: "food-038", category: "food", setup: "Why did the donut go to the dentist?", punchline: "To get a filling!" },
  { id: "food-039", category: "food", setup: "What kind of shoes do bananas wear?", punchline: "Slippers!" },
  { id: "food-040", category: "food", setup: "Why did the waffle go to the gym?", punchline: "To get square!" },
  { id: "food-041", category: "food", setup: "What's a corn's favorite music?", punchline: "Pop music!" },
  { id: "food-042", category: "food", setup: "Why did the salad go to church?", punchline: "To get dressed!" },
  { id: "food-043", category: "food", setup: "What do you call a sad coffee?", punchline: "Depresso!" },
  { id: "food-044", category: "food", setup: "Why did the orange go out with the prune?", punchline: "Because it couldn't get a date!" },
  { id: "food-045", category: "food", setup: "What's a tree's favorite drink?", punchline: "Root beer!" },
  { id: "food-046", category: "food", setup: "Why did the bread feel warm?", punchline: "It was toasty!" },
  { id: "food-047", category: "food", setup: "What do you call a fake potato?", punchline: "An imi-tater!" },
  { id: "food-048", category: "food", setup: "Why did the pea blush?", punchline: "It saw the salad dressing!" },
  { id: "food-049", category: "food", setup: "What's a frog's favorite candy?", punchline: "Lollihops!" },
  { id: "food-050", category: "food", setup: "Why did the bagel go to the party?", punchline: "Because it was on a roll!" },
  { id: "food-051", category: "food", setup: "What do you call an angry pancake?", punchline: "A hotcake!" },
  { id: "food-052", category: "food", setup: "Why did the yogurt go to art school?", punchline: "Because it was so cultured!" },
  { id: "food-053", category: "food", setup: "What's a snowman's favorite food?", punchline: "Ice Krispies!" },
  { id: "food-054", category: "food", setup: "Why did the cracker go to therapy?", punchline: "It was feeling salty!" },
  { id: "food-055", category: "food", setup: "What do you call a running turkey?", punchline: "Fast food!" },
  { id: "food-056", category: "food", setup: "Why did the meatball go to the party?", punchline: "Because it was well-rounded!" },
  { id: "food-057", category: "food", setup: "What's a basketball player's favorite food?", punchline: "Dunkin' Donuts!" },
  { id: "food-058", category: "food", setup: "Why did the soda feel flat?", punchline: "It lost its fizz-ique!" },
  { id: "food-059", category: "food", setup: "What do you call cheese that's acting crazy?", punchline: "Fondue-mental!" },
  { id: "food-060", category: "food", setup: "Why did the grape stop rolling?", punchline: "It ran out of juice!" },
  { id: "food-061", category: "food", setup: "What's a snake's favorite dessert?", punchline: "Pie-thon!" },
  { id: "food-062", category: "food", setup: "Why did the lemon feel sour?", punchline: "Someone squeezed it the wrong way!" },
  { id: "food-063", category: "food", setup: "What do you call a nervous apple?", punchline: "A crab apple!" },
  { id: "food-064", category: "food", setup: "Why did the pepper win the fight?", punchline: "It was jalapeño face!" },
  { id: "food-065", category: "food", setup: "What's a computer's favorite snack?", punchline: "Micro-chips!" },
  { id: "food-066", category: "food", setup: "Why did the carrot win an award?", punchline: "Because it was out-standing in its field!" },
  { id: "food-067", category: "food", setup: "What do you call a royal egg?", punchline: "An eggs-cellency!" },
  { id: "food-068", category: "food", setup: "Why did the soup get a promotion?", punchline: "It was souper good!" },
  { id: "food-069", category: "food", setup: "What's a pirate's favorite veggie?", punchline: "Arrrrtichokes!" },
  { id: "food-070", category: "food", setup: "Why did the spaghetti get in trouble?", punchline: "It was too saucy!" },
  { id: "food-071", category: "food", setup: "What do you call a happy candy bar?", punchline: "A Snickers!" },
  { id: "food-072", category: "food", setup: "Why did the bread go to the doctor?", punchline: "It was feeling a little crusty!" },
  { id: "food-073", category: "food", setup: "What's a cat's favorite breakfast?", punchline: "Mice Krispies!" },
  { id: "food-074", category: "food", setup: "Why did the pizza maker go broke?", punchline: "He just couldn't make enough dough!" },
  { id: "food-075", category: "food", setup: "What do you call a lazy steak?", punchline: "A meat loafer!" },
  { id: "food-076", category: "food", setup: "Why did the ice cream cone feel proud?", punchline: "Because it was on top!" },
  { id: "food-077", category: "food", setup: "What's a bird's favorite veggie?", punchline: "Beak-ons!" },
  { id: "food-078", category: "food", setup: "Why did the cookie feel smart?", punchline: "It was one smart cookie!" },
  { id: "food-079", category: "food", setup: "What do you call a spicy dinosaur?", punchline: "A raptor with pepper!" },
  { id: "food-080", category: "food", setup: "Why did the burger break up?", punchline: "There were too many issues to ketchup on!" },
  { id: "food-081", category: "food", setup: "What's a werewolf's favorite food?", punchline: "Howl-oween candy!" },
  { id: "food-082", category: "food", setup: "Why did the butter roll away?", punchline: "It was on a roll!" },
  { id: "food-083", category: "food", setup: "What do you call a sleeping pasta?", punchline: "Napsta!" },
  { id: "food-084", category: "food", setup: "Why did the bean feel musical?", punchline: "It was full of toots!" },
  { id: "food-085", category: "food", setup: "What's a skeleton's favorite snack?", punchline: "Spare ribs!" },
  { id: "food-086", category: "food", setup: "Why did the celery feel important?", punchline: "It was a big stalk!" },
  { id: "food-087", category: "food", setup: "What do you call a magical breakfast?", punchline: "Poof loops!" },
  { id: "food-088", category: "food", setup: "Why did the corn feel corny?", punchline: "It was full of corny jokes!" },
  { id: "food-089", category: "food", setup: "What's a ghost's favorite pie?", punchline: "Boo-berry pie!" },
  { id: "food-090", category: "food", setup: "Why did the salt cry?", punchline: "Someone shook it up!" },
  { id: "food-091", category: "food", setup: "What do you call a cold pizza?", punchline: "A freezy pleasy!" },
  { id: "food-092", category: "food", setup: "Why did the broccoli win the race?", punchline: "It was a head!" },
  { id: "food-093", category: "food", setup: "What's a rabbit's favorite food?", punchline: "Hop-corn!" },
  { id: "food-094", category: "food", setup: "Why did the pretzel feel twisted?", punchline: "It had a rough day!" },
  { id: "food-095", category: "food", setup: "What do you call a dancing chip?", punchline: "A salsa dancer!" },
  { id: "food-096", category: "food", setup: "Why did the milk go to the library?", punchline: "To become 2% smarter!" },
  { id: "food-097", category: "food", setup: "What's a dog's favorite pizza topping?", punchline: "Pupperoni!" },
  { id: "food-098", category: "food", setup: "Why did the cupcake feel blue?", punchline: "It was frosted out!" },
  { id: "food-099", category: "food", setup: "What do you call a mean burger?", punchline: "A bully beef!" },
  { id: "food-100", category: "food", setup: "Why did the egg feel confident?", punchline: "Because it was egg-straordinary!" },
];

/**
 * Get a random joke from the curated list, avoiding seen jokes
 */
export function getRandomJoke(
  category: JokeCategory = "all",
  seenJokeIds: string[] = []
): Joke {
  // Dad jokes come from API, not static list
  if (category === "dad-jokes") {
    // Return a placeholder - actual dad jokes fetched async
    return {
      id: "dad-loading",
      category: "dad-jokes" as Exclude<JokeCategory, "all">,
      setup: "Loading dad joke...",
      punchline: "",
    };
  }

  const allJokes = category === "all"
    ? CURATED_JOKES
    : CURATED_JOKES.filter((j) => j.category === category);

  // Filter out seen jokes
  const unseenJokes = allJokes.filter((j) => !seenJokeIds.includes(j.id));

  // If all jokes seen, reset and use all jokes
  const jokes = unseenJokes.length > 0 ? unseenJokes : allJokes;

  const randomIndex = Math.floor(Math.random() * jokes.length);
  return jokes[randomIndex];
}

/**
 * Fetch a dad joke from icanhazdadjoke.com API
 */
export async function fetchDadJoke(): Promise<Joke> {
  try {
    const res = await fetch("https://icanhazdadjoke.com/", {
      headers: { Accept: "application/json" },
    });
    const data = await res.json();
    return {
      id: `dad-${data.id}`,
      category: "dad-jokes" as Exclude<JokeCategory, "all">,
      setup: data.joke,
      punchline: "", // Dad jokes are single-line
    };
  } catch {
    // Fallback if API fails
    return {
      id: "dad-fallback",
      category: "dad-jokes" as Exclude<JokeCategory, "all">,
      setup: "Why don't scientists trust atoms? Because they make up everything!",
      punchline: "",
    };
  }
}

/**
 * Get all jokes for a category
 */
export function getJokesByCategory(category: JokeCategory): Joke[] {
  if (category === "all") return CURATED_JOKES;
  if (category === "dad-jokes") return []; // Dad jokes are API-only
  return CURATED_JOKES.filter((j) => j.category === category);
}
